### ISSUE TITLE
Doesn't work on localhost

### ISSUE THREAD

**Issue by andrew-ireland** [subpixel-ch/statamic-favicon#2]
Hey there 👋  

First of all, thank you for your work on this addon, it's an excellent addition to statamic!

I've just installed it on a couple of dev sites I'm working on, however, I run into the following issue on realfavicongenerator.net when using it on my local server (using valet/browsersync):

> Cannot download picture at http://devlink.test/assets/site_assets/favicon.svg
> 
> If you fill there is something wrong, please contact us, describe what you were doing and insert the following text in your email, it will help us spot the error:
> 
> {"favicon_generation":{"api_key":"c77c53d82249fef14cfbc95816e075af6f8c07e3","master_picture":{"demo":false,"type":"url","url":"http:\/\/devlink.test\/assets\/site_assets\/favicon.svg"},"files_location":{"type":"path","path":"\/assets\/favicon"},"callback":{"type":"url","url":"http:\/\/hampton.test\/cp\/addons\/favicon\/callback"}}}

I realise this addon hasn't been updated in some time, but just wanted to bring the error to your attention, in case there any simple fix you can implement to make this work locally? 

Best,
Andrew

**Comment by rrelmy** [comment]
Hi Andrew

The reason is that `.test` is not recognised as local development domain.
Because of performance and limitations the favicon generator accepts the raw image as URL or Base64 encoded. When possible the addon sends a URL but that does not work for local only domains.

I will update the check and release a new version in a moment.

Regards
Rémy

**Comment by andrew-ireland** [comment]
Hey @rrelmy, Thank you for the update! This works perfectly on my end now 👍
